server:
  port: 8080
  
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3307/jwt_authentication?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
    show-sql: true
    
auth:
  jwt:
    expiration: 86400000
    secret: secret